apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: n8n-service-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: public
    nginx.ingress.kubernetes.io/app-root: /
spec:
  rules:
    - http:
        paths:
          - path: /n8n
            pathType: Prefix
            backend:
              service:
                name: n8n-service
                port:
                  number: 80
