apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mage-ai-pvc
spec:
  accessModes: [ReadWriteOnce]
  resources: { requests: { storage: 10Gi } }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mage-server
spec:
  selector:
    matchLabels:
      app: mage-server
  volumes:
  - name: pvc
    persistentVolumeClaim:
      claimName: mage-ai-pvc
  replicas: 1
  template:
    metadata:
      labels:
        app: mage-server
    spec:
      serviceAccountName: mage-user
      containers:
        - name: mage-server
          image: mageai/mageai:latest
          ports:
            - name: web
              containerPort: 6789
          volumeMounts:
          - name: pvc
            mountPath: /home/src
          env:
            - name: KUBE_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace

