apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: mongo-secret
  namespace: default
  labels:
    app: mongo
    component: secrets
stringData:
  # Database password
  root_username: "admin"
  root_password: "Passw0rd"
